version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hmct"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xyaj163kmnuo"
s3_prefix = "sam-hmct"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
