version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hmct"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xyaj163kmnuo"
s3_prefix = "sam-hmct"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
parameter_overrides = "AppName=\"hmctech\" ClientDomains=\"http://localhost:3000\" AdminEmail=\"jgregan93@gmail.com\" AddGroupsToScopes=\"true\" UserPoolId=\"eu-west-1_wLfnEbIdY\" Audience=\"6jgqjs8ri2iemd1q3ghemu5otv\""
